// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type CheckoutResult struct {
	Purchased []*Pet `json:"purchased"`
}

type CreatePetInput struct {
	Name        string  `json:"name"`
	Species     Species `json:"species"`
	Age         int     `json:"age"`
	PictureURL  string  `json:"pictureUrl"`
	Description string  `json:"description"`
}

type Mutation struct {
}

type Pet struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Species     Species   `json:"species"`
	Age         int       `json:"age"`
	PictureURL  string    `json:"pictureUrl"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
}

type Query struct {
}

type SoldPet struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Species     Species   `json:"species"`
	Age         int       `json:"age"`
	PictureURL  string    `json:"pictureUrl"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	SoldAt      time.Time `json:"soldAt"`
}

type Species string

const (
	SpeciesCat  Species = "CAT"
	SpeciesDog  Species = "DOG"
	SpeciesFrog Species = "FROG"
)

var AllSpecies = []Species{
	SpeciesCat,
	SpeciesDog,
	SpeciesFrog,
}

func (e Species) IsValid() bool {
	switch e {
	case SpeciesCat, SpeciesDog, SpeciesFrog:
		return true
	}
	return false
}

func (e Species) String() string {
	return string(e)
}

func (e *Species) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Species(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Species", str)
	}
	return nil
}

func (e Species) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Species) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Species) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
