package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/petstore/backend/graph/model"
	"github.com/petstore/backend/internal/auth"
	"github.com/petstore/backend/internal/db"
)

// CreatePet is the resolver for the createPet field.
func (r *mutationResolver) CreatePet(ctx context.Context, input model.CreatePetInput) (*model.Pet, error) {
	user, err := auth.RequireMerchant(ctx)
	if err != nil {
		return nil, err
	}
	if input.Name == "" || input.PictureURL == "" || input.Description == "" {
		return nil, fmt.Errorf("name, pictureUrl, and description are required")
	}
	if input.Age < 0 {
		return nil, fmt.Errorf("age must be non-negative")
	}
	pet, err := r.Repo.CreatePet(ctx, *user.StoreID, input.Name, db.Species(input.Species), input.Age, input.PictureURL, input.Description)
	if err != nil {
		return nil, err
	}
	return petToModel(*pet), nil
}

// DeletePet is the resolver for the deletePet field.
func (r *mutationResolver) DeletePet(ctx context.Context, id string) (bool, error) {
	user, err := auth.RequireMerchant(ctx)
	if err != nil {
		return false, err
	}
	petID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid pet id: %s", id)
	}
	if err := r.Repo.DeletePet(ctx, *user.StoreID, petID); err != nil {
		return false, err
	}
	return true, nil
}

// PurchasePet is the resolver for the purchasePet field.
func (r *mutationResolver) PurchasePet(ctx context.Context, store string, petID string) (*model.Pet, error) {
	user, err := auth.RequireCustomer(ctx)
	if err != nil {
		return nil, err
	}
	id, err := uuid.Parse(petID)
	if err != nil {
		return nil, fmt.Errorf("invalid pet id: %s", petID)
	}
	pet, err := r.Repo.PurchasePet(ctx, user.ID, store, id)
	if err != nil {
		return nil, err
	}
	return petToModel(*pet), nil
}

// Checkout is the resolver for the checkout field.
func (r *mutationResolver) Checkout(ctx context.Context, store string, petIds []string) (*model.CheckoutResult, error) {
	user, err := auth.RequireCustomer(ctx)
	if err != nil {
		return nil, err
	}
	if len(petIds) == 0 {
		return nil, fmt.Errorf("petIds must be a non-empty list")
	}
	ids := make([]uuid.UUID, 0, len(petIds))
	for _, raw := range petIds {
		id, err := uuid.Parse(raw)
		if err != nil {
			return nil, fmt.Errorf("invalid pet id: %s", raw)
		}
		ids = append(ids, id)
	}
	purchased, err := r.Repo.Checkout(ctx, user.ID, store, ids)
	if err != nil {
		return nil, err
	}
	return &model.CheckoutResult{Purchased: petsToModel(purchased)}, nil
}

// UnsoldPets is the resolver for the unsoldPets field.
func (r *queryResolver) UnsoldPets(ctx context.Context) ([]*model.Pet, error) {
	user, err := auth.RequireMerchant(ctx)
	if err != nil {
		return nil, err
	}
	pets, err := r.Repo.UnsoldPets(ctx, *user.StoreID)
	if err != nil {
		return nil, err
	}
	return petsToModel(pets), nil
}

// SoldPets is the resolver for the soldPets field.
func (r *queryResolver) SoldPets(ctx context.Context, startDate time.Time, endDate time.Time) ([]*model.SoldPet, error) {
	user, err := auth.RequireMerchant(ctx)
	if err != nil {
		return nil, err
	}
	if endDate.Before(startDate) {
		return nil, fmt.Errorf("endDate must be on or after startDate")
	}
	sold, err := r.Repo.SoldPets(ctx, *user.StoreID, startDate, endDate)
	if err != nil {
		return nil, err
	}
	return soldPetsToModel(sold), nil
}

// AvailablePets is the resolver for the availablePets field.
func (r *queryResolver) AvailablePets(ctx context.Context, store string) ([]*model.Pet, error) {
	if _, err := auth.RequireCustomer(ctx); err != nil {
		return nil, err
	}
	// surface a distinct error when the store doesn't exist
	if _, err := r.Repo.StoreBySlug(ctx, store); err != nil {
        return nil, err 
    }
	pets, err := r.Repo.AvailablePetsByStoreSlug(ctx, store)
	if err != nil {
		return nil, err
	}
	return petsToModel(pets), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
